### ISSUE TITLE
Resuming work on pdfsizeopt?

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#1]
Hi, @pts.

I see that the repository on google was closed. That being said, I thought that, perhaps, one might want to resume work on pdfsizeopt.

I would like to contribute, but I would also like to use some features that are only present in newer versions of Python. What should I do?

Thanks,
Rogério Brito.

**Comment by pts** [comment]
It's not obvious how we can make progress here.

If you want to contribute to argument parsing, please open a separate bug for that.

> BTW, even though argparse is handy, the user interface would be
changed, so that "backwards compatibility" for existent users would be
broken. Is that OK with you?

I assumed argparse is flexible enough to keep most of the existing behavior. Small, long-tail breakages are fine for me.
