### ISSUE TITLE
Don't bother with 1-bit PNG by default

### ISSUE THREAD

**Issue by peripatetes** [pts/pdfsizeopt#104]
A common use case is shrinking PDFs with Group 4 B&W images by converting them to jbig2. 

I imagine that the proportion of 1-bit images which are smaller as PNG is very low. Right now, running pdfsizeopt on a file with B&W images will by default spend almost all of its time in pngout only to find that the output of pngout is reliably more than twice as big as a jbig2 version, so all that work is discarded. Why not make it default behavior to ignore PNG for images that can be compressed with jbig2?

**Comment by rbrito** [comment]
@peripatetes, yes, this is my experience, especially when compressing now up to HUNDREDS of gigs of scanned documents.

I created the following commit on my repository and it has been working wonderfully for the last 8 or 9 months: https://github.com/rbrito/pdfsizeopt/commit/87fe1339b4b4cda52b192d919d6be175c4af5353

I intend to push it to @pts (separately from the other commits on that branch) and, if he accepts it, other people with benefit from much better speeds with (almost) no drop in compression in speed.

**Comment by pts** [comment]
The design philosophy of pdfsizeopt is trying all available optimizations (rather than trying to be smart about what optimizations to skip). Adding a heuristic to skip pngout in some cases would go against this philosophy, so it will not be enabled by default. (Also, have you compared pngout to jbig2 for small, e.g. 10x10, 20x20, 40x40 images?)

However, I'm open to adding this functionality with some non-default flag, e.g. `--use-pngout=if-not-jbig2`.

**Comment by rbrito** [comment]
@pts, I didn't send a pull request yet exactly because I suspected that you didn't want this option turned on unconditionally (you can see that it was written about 8 or 9 months ago) and was exactly thinking of a good name for an option.

I did use something like `--use-image-optimizer=jbig2` to optimize some files that I had here, but with files of scanned documents that are about 50% black-and-white and grayscale, the missed oportunity of not running something like `optipng` was actually not acceptable and I ended up with that patch of mine and it has suited me really well (especially when compressing many, many files).

BTW, I would prefer an option with a name more agnostic for bilevel images, without using the name of a specific tool like pngout (perhaps `--skip-deflate-for-bilevel-images=yes`).

What do you think about this? I would like to have a pull request of mine accepted for pdfsizeopt, just to give back to your excellent tool!

**Comment by pts** [comment]
`--skip-deflate-for-bilevel-images=yes` would be misleading, because sam2p is also emitting flate-compressed images (sam2p_np emits PDF, sam2p_pr emits PNG), and it's not easy to disable sam2p.

Here is my suggestion:

* The flag should be `--do-fast-bilevel-images=yes` with the help text: *Disable some slow image optimizers for bilevel images in favor of jbig2. This flag is smart, and it disables optimizers only if jbig2 is enabled, and the to-be-disabled optimizer is very unlikely to be better than jbig2.*
* If the flag is true, and 16384 <= width * height < 65536, and jbig2 is enabled, and the output of sam2p_pr indicates that the image is bilevel, then the following optimizers get disabled for this image: pngout, zopflipng, optipng*, ect, advpng*, pngwolf.
* If the flag is true, and width * height >= 65536, and jbig2 is enabled, and the output of sam2p_np indicates that the image is bilevel, then all other optimizers get disabled (except for sam2p_np, sam2p_pr and jbig2) for this image. For further speedup in a subsequent pull request, instead of sam2p_pr, ImgData.SavePng is used on the output of sam2p_np, with zlib compression level set to 3 (fast). The Python code of SavePng needs to be extended for specifying the zlib compression level, also a `'\0'` byte (indicating the None predictor) has to be inserted to the idat in front of each line of the output PNG.
* Otherwise the current behavior is unchanged: all configured optimizers are run.

Important to pay attention to:

* Always use the output of sam2p_np or sam2p_pr to detect whether the image is bilevel. Other source and intermediary images may be unoptimized (e.g. representing a bilevel image as RGB).
* For small images, flate (by e.g. sam2p_np) or even uncompressed can be better than jbig2, so don't disable any optimizers.

Pull requests are always welcome.

**Comment by pts** [comment]
Please give the newly implemented `--do-fast-bilevel-images=yes` a try.

**Comment by pts** [comment]
FYI Commit 83c8ee17df4254dc378f16ed6c0309837b339d7a adds even more speedups when `--do-fast-bilevel-images=yes` is enabled: in when the input is in the correct format (bilevel PNG) for jbig2, then sam2p_np and save_oi are skipped, and only jbig2 is run.

**Comment by peripatetes** [comment]
Thanks! On the file I tried, this was at least a 100x speedup (don't know exactly because I terminated the slow job after waiting a long time). Status messages told that the PNGOUT versions were double the size of the original Group 4 and 3x as large as the jbig2, so the speedup certainly didn't come at the cost of size.

I do think that you should consider making this the default. (Though I can understand waiting until you feel certain the size thresholds are what you want.) I know pdfsizeopt tries to err somewhat on the side of exhaustive search, but you don't try every single image format even though it's conceivable that some images will be smaller as LZW or RLE than Flate, so you're already using some heuristics to only consider changes that are likely to reduce size.
