### ISSUE TITLE
Optimizing Latge Files

### ISSUE THREAD

**Issue by Clifra-Jones** [pts/pdfsizeopt#116]
I have a project where Ineed to optimize some large PDFs that have been exprted out of a Document Managemet system. Things were goin along fine and I have about 80% of the library done but now I am getting this error on files I am trying to optimize.

```
info: This is pdfsizeopt ZIP rUNKNOWN size=69649.
info: prepending to PATH: C:\pdfsizeopt_win32exec-v6\pdfsizeopt_win32exec
info: loading PDF from: f:\exports\EmployeeFile\tpdf-AGUILAR L ENRIQUE_4415.PDF
Traceback (most recent call last):
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt_win32exec\python26.zip\runpy.py", line 122, in _run_module_as_main
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt_win32exec\python26.zip\runpy.py", line 34, in _run_code
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt.single\__main__.py", line 1, in <module>
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt.single\m.py", line 6, in <module>
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt.single\pdfsizeopt\main.py", line 5610, in main
  File "C:\pdfsizeopt_win32exec-v6\pdfsizeopt.single\pdfsizeopt\main.py", line 2566, in Load
MemoryError
```

This is my command line: `pdfsizeopt --use-pngout=no {source} {target}`

**Comment by Clifra-Jones** [comment]
Well, I seemed to have fixed it by changing a few parameters on the MAG to PDF conversion program I was using. nconvert.exe, Nuts have been the large file size. This reduced the file size before running pdfsizeopt.

Thanks.

**Comment by pts** [comment]
pdfsizeopt reads the entire PDF file to memory, does each optimization step in-memory (creating temporary data structures on the fly and discarding them early), and writes the optimized PDF to disk. So a large input PDF file causes large memory usage, possibly causing the *MemoryError* you've experienced. Workarounds are: split the input PDF file and process it separately; add more memory to the system; disable some optimization steps using command-line flags.

It would be very hard to change pdfsizeopt to make it able to process input PDF files which don't fit to memory.

**Comment by Ndolam** [comment]
On Fri, May  3, 2019 at 15:50 (-0700), PÃ©ter SzabÃ³ wrote:

> pdfsizeopt reads the entire PDF file to memory, does each
> optimization step in-memory (creating temporary data structures on
> the fly and discarding them early), and writes the optimized PDF to
> disk. So a large input PDF file causes large memory usage, possibly
> causing the *MemoryError* you've experienced. Workarounds are: split
> the input PDF file and process it separately; add more memory to the
> system; disable some optimization steps using command-line flags.

> It would be very hard to change pdfsizeopt to make it able to process input PDF files which don't fit to memory.

I've never peeked at the source code, but would memory mapping the
input file be a possibility?  At the possible cost of reading some
pages from disk multiple times (for "big" files only?), the system
might be better able to deal with really large PDFs.

Or is the file parsed upon reading it so that the on-disk byte
sequence is not of much use?

Cheers.
                                Jim

**Comment by pts** [comment]
> Or is the file parsed upon reading it so that the on-disk byte sequence is not of much use?

Yes, the PDF file is parsed upon reading. Some parts of the PDF file (e.g. images) are compressed blobs. It would be possible to skip over the blobs (without reading them to memory) at parse time, and later read and decompress the blobs one-by-one on demand. This way only a few blobs (rather than all of them) would be kept in memory at any given time, thus saving memory for input PDFs with many and/or large blobs. It's feasible to implement this optimization in pdfsizeopt, but to make it happen, pdfsizeopt has to get funding and/or volunteers first.
