### ISSUE TITLE
using CPDF before or after PSO

### ISSUE THREAD

**Issue by maadjordan** [pts/pdfsizeopt#119]
referring to pdf tool called CPDF at https://github.com/johnwhitington/cpdf-source 
I've tested the following command line:
cpdf -compress -no-preserve-objstm -remove-duplicate-streams -fix-prince -remove-duplicate-fonts  -remove-metadata -no-embed-font -squeeze "input" -o "output"

I got some saving occasionally by using it before PSO but using it after will rarely make any same.

**Comment by pts** [comment]
Thank you for this feedback!

I'm closing thus issue because I can't see any immediate action which could be taken to improve pdfsizeopt. Feel free to reopen it if you have specific recommendations.

**Comment by maadjordan** [comment]
additional benefit of using CPDF it can repair and reconstruct bad or damaged streams that resulted into pdfsizeopt make a succesful optimization instead of generating error.

**Comment by zvezdochiot** [comment]
@maadjordan say> cpdf ...

Very useful info!

**Comment by maadjordan** [comment]
Also Qpdf has reconstruction abilities.. to be considered too

**Comment by zvezdochiot** [comment]
@maadjordan say> Qpdf has reconstruction abilities

Details in the studio, please.

**Comment by maadjordan** [comment]
studio ?

**Comment by zvezdochiot** [comment]
@maadjordan say> studio ?

This is a figurative expression, an example is expected.

**Comment by maadjordan** [comment]
i am still testing as i am getting different results

**Comment by maadjordan** [comment]
sample file: http://www.arvindguptatoys.com/arvindgupta/paper-polyhedra.pdf
Original 2,626,880 bytes
PSO 342,473 bytes
CPDF 344,856 bytes
PSO+CPDF 340,916 bytes
CPDF+PDF 342,051 bytes

this file cpdf after pso is best

**Comment by zvezdochiot** [comment]
@maadjordan say> CPDF+PDF 342,051 bytes

Maybe CPDF+QPDF? And options QPDF?

**Comment by maadjordan** [comment]
currently using

cpdf -compress -no-preserve-objstm -remove-duplicate-streams -fix-prince -remove-duplicate-fonts  -remove-metadata -no-embed-font -squeeze "%i" -o "%i.cpd"

pdfsizeopt --v=20 --use-pngout=No --use-image-optimizer=ECT --use-multivalent=YES --do-fast-bilevel-images=Yes --tmp-dir=d:\temp "%i" "%i.pso"

**Comment by zvezdochiot** [comment]
@maadjordan say> currently using

Not. Interested "Qpdf has reconstruction abilities".

**Comment by rbrito** [comment]
Just for the record, if I use qpdf (a tool that pdfsizeopt already
uses/recommends, at least for encrypted files) to uncompress the original
PDF file before feeding it to pdfsizeopt, but then I can get (frequently,
but not always) some extra compression gains instead of simply running
pdfsizeopt directly.

I suspect that the gains (sometimes, substantial, other times, smaller)
come from the recompression with deflate at higher levels than the
originals.

I noticed this fact mainly with books from Packt and O'Reilly, but it also
applies to other publishers too.

I modified my own copy of pdfsizeopt to never use what Péter calls "low
effort" (or something similar in the source code) and always use level 9 of
deflate.

If I recall correctly, Péter decides, sometimes, to use level 9, sometimes
to use level 3. The "standard" is to always use level 6.

My copy has also some slight tweaks to be more lenient with defective
palette sizes and so on...


I will add more comments as soon as I have some more free time.

Regards,

Rogério Brito.


Em dom, 30 de jun de 2019 12:36, звездочёт <notifications@github.com>
escreveu:

**Comment by zvezdochiot** [comment]
@rbrito say> I will add more comments as soon as I have some more free time.

Good, thank.

**Comment by pts** [comment]
> I modified my own copy of pdfsizeopt to never use what Péter calls "low
effort" (or something similar in the source code) and always use level 9 of
deflate.

@rbrito, please file a separate issue for this. pdfsizeopt should be able to recompress all flate streams with effort 9, and probably that should be the default.
