### ISSUE TITLE
migrate to Python 3

### ISSUE THREAD

**Issue by doronbehar** [pts/pdfsizeopt#139]
README says `pdfsizeopt` isn't supported by python 3.x. Are there any plans to upgrade to Python3?

**Comment by zvezdochiot** [comment]
https://github.com/pts/pdfsizeopt/blob/33ec5e5c637fc8967d6d238dfdaf8c55605efe83/pdfsizeopt#L25-L28

**Comment by pts** [comment]
Most users of pdfsizeopt shouldn't care, because on Windows pdfsizeopt ships with a copy of Python 2.6 embedded, and on Linux and macOS Python 2 is still available and preinstalled (as of 2020-02-19).

There is no technical reason why pdfsizeopt can't be migrated to Python 3. It's just takes time and effort. It's unlikely to happen unless pdfsizeopt receives funding.

**Comment by pts** [comment]
Update: Now the Linux, macOS and Windows helper programs (part of the installation instructions) all contain a copy of Python 2, so pdfsizeopt will work on systems where Python 2 is not installed (i.e. most modern systems nowadays).

**Comment by malespiaut** [comment]
Hello,

I'm commenting on this issue because I consider that it shouldn't be closed. In my humble opinion, relying on Python 2, or Docker, is not a viable option.

Although I perfectly understand that migrating to Python 3 needs time, effort, and money, I've been unable to use pdfsizeopt on my machine. I'm sad to now consider pdfsizeopt as unusable.

**Comment by GhostDog98** [comment]
Agreed, python2.7 has been EOL since ***2020***.
Additionally, it is no longer receiving security patches, and as such has many unpatched CVEs...

**Comment by Ndolam** [comment]
Anyone here expert enough with an AI programming assistant to ask it to convert the codebase from Python2 to Python3?  

(The one time I tried it, I found out that I was AI-programming-assistant-challenged, but I'm guessing someone reading this is good at it.)
