### ISSUE TITLE
No compression results

### ISSUE THREAD

**Issue by kylefoley76** [pts/pdfsizeopt#147]
I tried to compress a PDF of 1.7 megs, the output was also 1.7 megs.  I'm using a MacOS.  PDF in question is attached.
[stace22.pdf](https://github.com/pts/pdfsizeopt/files/5764389/stace22.pdf)

**Comment by zvezdochiot** [comment]
@kylefoley76 say:
>stace22.pdf

String 17:
```pdf
/Filter /DCTDecode
```
This is JPEG. See #95 .

**Comment by rbrito** [comment]
Using the scripts ([using_pikepdf.py][1] and [optimize_jpegs.py][2]) that I posted on [a repository of mine][3], I can optimize the file to have 1168993 bytes. I'm attaching it here.

[1]: https://github.com/rbrito/scripts/blob/master/using_pikepdf.py
[2]: https://github.com/rbrito/scripts/blob/master/optimize_jpegs.py
[3]: https://github.com/rbrito/scripts/
[stace22.psom.pso.pdf](https://github.com/pts/pdfsizeopt/files/5767227/stace22.psom.pso.pdf)

**Comment by rbrito** [comment]
These scripts of mine are to be used before a run with `pdfsizeopt`.

**Comment by copyme** [comment]
@rbrito cool very useful scripts!

**Comment by pts** [comment]
FYI New version of the scripts of @rbrito is available at: https://github.com/rbrito/scripts/blob/master/optimize_pdfs.py

Why doesn't pdfsizeopt make the attached PDF file much smaller? Because that PDF contains mostly JPEG images, and JPEG image optimization hasn't been implemented in pdfsizeopt yet (see https://github.com/pts/pdfsizeopt/issues/41 tracking it). See also https://github.com/pts/pdfsizeopt/issues/95 tracking lossy JPEG image optimization.
