### ISSUE TITLE
Calling pdfsizeopt out of Emacs: "info: this Ghostscript does not work"

### ISSUE THREAD

**Issue by Keks-Dose** [pts/pdfsizeopt#15]
I've been using pdfsizeopt on Windows and Linux for years. After a fresh installation of the Win 8.1 PC, pdfsizeopt can no longer be called from Emacs! I went to emacs.stackexchange.com, [asked](https://emacs.stackexchange.com/questions/32368/on-windows-8-1-in-emacs-ghostscript-doesnt-work-while-on-commandline-it-does), even offered a bounty, no result. 

I can call pdfsizeopt from command line, no problem. But called from Emacs, I only get the error message that Ghostscript does not work. 

I'd be very glad to get it working again. For the details, would you please have a look at the above mentioned post at emacs.stackexchange.com? 

Any help much appreciated!

**Comment by pts** [comment]
Your `$PATH` environment variable within Emacs is probably wrong.

According to the error messages in https://emacs.stackexchange.com/questions/32368/on-windows-8-1-in-emacs-ghostscript-doesnt-work-while-on-commandline-it-does , when you run pdfsizeopt from the command-line, it finds `"C:\Program Files (x86)\gs\gs9.21\bin\gswin32c.exe"`, but when you run it from Emacs, it can't find `gswin32c.exe`, probably because the `$PATH` is wrong.

One way to fix it is fixing the `$PATH` within Emacs (I have no idea about this, I'm not an Emacs or Windows 8.1 expert.).

Another fix which may also work is following the *Installation instructions and usage on Windows* on https://github.com/pts/pdfsizeopt . This way pdfsizeopt has a bundled `gswin32c.exe`, which it may be able to find even without a working `$PATH`.

**Comment by Keks-Dose** [comment]
Found a wrong path to gswin32c.exe in the registry, probably my own mistake. Sorry for the noise, thank you for your comment and, besides this, thank you very much for pdfsizeopt!
