### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by copyme** [pts/pdfsizeopt#150]
As in the title. I find the ```pdfsizeopt``` very useful but it seems like it has not gotten any update in a while.

**Comment by pts** [comment]
This project (https://github.com/pts/pdfsizeopt) hasn't been getting many updates recently because the primary author (@pts) nowadays devotes most of their free time for other activities, and the project hasn't received funding for active full-time or part-time work.

It is the goal of @pts to keep the program working on newer systems (e.g. Macs with Apple Silicon recently), but it's unlikely that pdfsizeopt will receive many new features until the funding situation changes or new volunteers start working on it.

**Comment by pts** [comment]
Thank you for using *pdfsizeopt*! If you need some new features or to get some bugs fixed, please report individual issues for them.
