### ISSUE TITLE
Why pngout is using the force flag?

### ISSUE THREAD

**Issue by albertopasqualetto** [pts/pdfsizeopt#155]
Why png compression is using `pngout -force *` command?
From what I understood that flag is going to create the output also if the output is larger than the input, which is nosense from a size compression point of view.

**Comment by pts** [comment]
> Why png compression is using `pngout -force *` command?

This is in implementation detail of pdfsizeopt. Using the `-force` flag won't actually increase the final image size, because pdfsizeopt records the output image size of each image optimizer (and also the original image size), and picks the smallest.

Why is running `pngout -force` flag useful for pdfsizeopt? By doing so, pdfsizeopt can distinguish these 3 cases: (1) pngout exists, it has processed the image, and made it smaller; (2) pngout exists, it has processed the image, and made it larger; (3) pngout doesn't exist on the system or it has encountered a runtime error (such as input file not found, output filesystem full, out of memory) processing the image. Without the `-force` flag, pdfsizeopt wouldn't be able to distinguish (2) and (3).
