### ISSUE TITLE
Error of ioerror

### ISSUE THREAD

**Issue by FrankEular** [pts/pdfsizeopt#16]
[pdfsizeopt.txt](https://github.com/pts/pdfsizeopt/files/1052374/pdfsizeopt.txt)
The pdf file in question:
https://www.dropbox.com/s/ftmn5jei2lxelma/bok%253A978-3-662-08005-4.pdf?dl=0

WARNING: This pdf file is ONLY used to debug pdfsizeopt. Due to the copyright, one is NOT authorized to spread/distribute this file, or upload to somewhere.

**Comment by pts** [comment]
Thank you for reporting this bug!

I've diagnosed the problem with this PDF file. It contains the /Helvetica-Oblique font with a weird duplicate `definefont` invocation, which also defines (overrides) the /Helvetica font:

Instead of just:
```
dup/FontName get exch definefont pop
```
... it has:
```
dup/FontName get exch definefont pop
dup/CharStrings /Helvetica findfont/CharStrings get put
dup/FontName get exch definefont pop
```

There may be a workaround (to be implemented within pdfsizeopt), but I haven't found it yet.

**Comment by pts** [comment]
Commit 912732b7dc5975be63350a7361b7986405c8b73a fixes the font processing error `/MultipleFontsDefined' with the font /Helvetica-Oblique.

However, there is another error with this PDF file, one of the scanned images are corrupt (i.e. they are incorrectly compressed, Ghostscript cannot decode them). The relevant error about object 314 on page 82 is:

```
AssertionError: Error in image data: XObject 341 width=3661 height=5551 bpc=1 colorspace=/DeviceGray filter=/CCITTFaxDecode decodeparms=<< /K -1 /Columns 3661 >> device=pngmono
```

This is a little bit odd, because Ghostscript 9.05 and 9.10 are not able load the image (with error `**** Warning: File has insufficient data for an image.`), but Evince is, and gv also is (please note that gv uses Ghostscript).

**Comment by pts** [comment]
The offending page is the page with number 76 in the top left corner. As you can see there, only the first 25% of the page is present: the line below the line *ful to compare...* is partially missing, and everything below is missing. So this is a PDF with a corrupt image, thus it is a corrupt PDF.

pdfsizeopt doesn't promise anything on processing corrupt PDFs, thus technically it's working as intended now on this input.

**Comment by pts** [comment]
I was able to add a workaround to pdfsizeopt so that it now works with corrupt images. It ran on your file successfully:
```
$ pdfsizeopt --use-pngout=no bok%3A978-3-662-08005-4.pdf
...
info: saved 7328151 bytes (28%) on optimizable images
info: compressed 1 streams, kept 1 of them uncompressed
info: saving PDF with 1340 objs to: bok%3A978-3-662-08005-4.pso.pdf
info: generated object stream of 9194 bytes in 384 objects (4%)
info: generated 21294758 bytes (74%)
```

Please download the latest pdfsizeopt.single file (version 606b42fd068a9a9eb532c3563862f154c69a0c23 or later).
