### ISSUE TITLE
Unrecoverable error while dealing with fonts

### ISSUE THREAD

**Issue by FrankEular** [pts/pdfsizeopt#19]
$ pdfsizeopt --use-pngout=no foo.pdf

The log is uploaded.
[pdfsizeopt.txt](https://github.com/pts/pdfsizeopt/files/1082647/pdfsizeopt.txt)

The PDF file: https://www.dropbox.com/s/q3qqoku625yfwvm/bok%253A978-1-4612-6153-7.pdf?dl=0
WARNING: Due to the copyright, this PDF file is only used to debug. One isn't authorized to diffuse.

**Comment by pts** [comment]
Thank you for reporting this bug! I was able to reproduce the problem.

Please use `pdfsizeopt --do-unify-fonts=no --do-regenerate-all-fonts=no` until this bug is fixed.

**Comment by pts** [comment]
The problem seems to be caused by the *GVGNTR+HiddenHorzOCR* font in obj 79, which the Type1CParser of pdfsizeopt isn't able to parse. Currently Ghostscript running the Type1CParser is silently substituting the default font (*Nimbus Mono L Regular*) instead of this font. This is definitely a bug, the correct behavior would be showing a warning message about the font, and moving on without optimizing it.

**Comment by pts** [comment]
Fixed in 84ae024167a61b00784e99ecdd342f71c729decd, please upgrade to the latest pdfsizeopt and enjoy the warning message (instead of a fatal error) on unparsable fonts.
