### ISSUE TITLE
wrong glyph because the encoding in the font program wasn't merged to the /Type/Font /Encoding /Differences

### ISSUE THREAD

**Issue by lemzwerg** [pts/pdfsizeopt#22]
[pdfsizeopt git 5eff1d37d4]

The attached PDF file can't be successfully converted; it replaces character 'ß' with '¢'.
[musikbegriffe.pdf](https://github.com/pts/pdfsizeopt/files/1104536/musikbegriffe.pdf)
[musikbegriffe.pso.pdf](https://github.com/pts/pdfsizeopt/files/1104537/musikbegriffe.pso.pdf)

**Comment by pts** [comment]
Thank you for reporting this bug!

Based on the files you've provided I was able to create a smaller PDF which exposes the same bug: [musik3.pdf](https://github.com/pts/pdfsizeopt/files/1105030/musik3.pdf) and [musik3.pso.pdf](https://github.com/pts/pdfsizeopt/files/1105031/musik3.pso.pdf)

Until this bug is fixed, please use `pdfsizeopt --do-unify-fonts=no --do-regenerate-all-fonts=no` as a workaround.

**Comment by pts** [comment]
I've fixed it in 03af633688ad091ed784ca83d5c7c545a005358a. Please upgrade pdfsizeopt and enjoy correct glyph selection.

Diagnosis: the encoding in the font program wasn't merged to the /Type/Font /Encoding /Differences. I've added code to do the merging.

**Comment by lemzwerg** [comment]
Verified. Thanks a lot for the very quick fix!
