### ISSUE TITLE
Missing image with /Filter/JBIG2Decode

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#32]
I reduced a file that generates a blank page (but it has OCR'ed text) to what I believe is the bare minimum and, since I belive this is a different problem than reported before, I am attaching it.

I have other, unrelated documents which seem to have the same behavior.

I am sorry if this is a duplicate of anything that I sent you earlier.

[p467.pdf](https://github.com/pts/pdfsizeopt/files/1251055/p467.pdf)

**Comment by pts** [comment]
Thank you for reporting this!

This PDF contains `/Filter/JBIG2Decode`, which doesn't seem to work with the Ghostscript called by the ImageRenderer component of pdfsizeopt. This is rather strange, because Ghostscript is able to render the image as part of a PDF. This is probably a Ghostscript bug, and needs further investigation before a workaround can be proposed.

**Comment by pts** [comment]
This is some weird Ghostscript bug, but I think I have a workaround now.

The bug happens if `/ReusableStreamDecode filter` is applied just before `/JBIG2Decode filter`, and the output size of the `/ReusableStreamDecode filter` is just as much as `/JBIG2Decode filter` wants to read. (If the output is longer, the bug doesn't happen.) With `/FlateDecode filter` etc. instead of `/JBIG2Decode filter`, the bug doesn't happen. I've verified the bug with Ghostscript 9.05 and 9.10.

Unfortunately, `GENERIC_PROCSET` used in RenderImages in pdfsizeopt is applying these filters like this, thus making the bug happen. The workaround I've found is adding (the no-op) `<< /CloseSource true >> _Length () /SubFileDecode filter` between the two filters. Before I commit the fix to pdfsizeopt, I'm verifying it on more PDFs.

**Comment by rbrito** [comment]
I have at least three files with the missing images. The three files are scanned documents.

Interestingly, in all three files, the missing images are just one page in the entire document. Do you want me to extract a few pages before and a few pages after the blank page, so that you can see the commonalities among them?

**Comment by rbrito** [comment]
[hardy-p265.pdf](https://github.com/pts/pdfsizeopt/files/1258751/hardy-p265.pdf)

**Comment by rbrito** [comment]
[hardy-p264-265.pdf](https://github.com/pts/pdfsizeopt/files/1258753/hardy-p264-265.pdf)
[hardy-p264-265.pso.pdf](https://github.com/pts/pdfsizeopt/files/1258754/hardy-p264-265.pso.pdf)

**Comment by pts** [comment]
Fixed (i.e. workaround implemented) in a2f0cca8d8629433f415ca2eb0a1d06a29a21b7a.

Fix verified for all .pdf files attached here and sent in e-mail.

Thank you very much for reporting this, and thank you for providing many input PDF files!
