### ISSUE TITLE
More blank images when processing PDF files

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#39]
Hi, @pts,

It seems that pdfsizeopt has problems processing at least one file that I just bought from O'Reilly promotion with humblebundle: https://www.humblebundle.com/books/data-science-books

The page in question is the following: 
[p040.pdf](https://github.com/pts/pdfsizeopt/files/1291201/p040.pdf)

I'm using `pdfsizeopt --use-pngout=no --use-multivalent=no p040.pdf` for compression, BTW.

I will be without Internet access during the next week, but I can try to provide any extra information that you may need.

I have other files that currently present problems with pdfsizeopt, but I will send them by alternate means.

**Comment by rbrito** [comment]
Another file, from another book that gives the same problem.

[p039.pdf](https://github.com/pts/pdfsizeopt/files/1291263/p039.pdf)

**Comment by rbrito** [comment]
And another page, from yet another book, giving the same (apparent) problem.

[p047.pdf](https://github.com/pts/pdfsizeopt/files/1291271/p047.pdf)

**Comment by pts** [comment]
Thank you very much for reporting these problems, and thank you for uploading single-page PDFs!

I'm trying to fix p040.pdf first. The problem is with the `/ColorSpace` value in the generated PDF. It's generated by the following call chain: PdfData.OptimizeImages calls ImageData.UpdatePdfObj calls ImageData.GetPdfImageData calls ImageData.GetPdfColorSpace calls PdfObj.EscapeString, which generates an incorrect PDF string literal if the binary version of the palette contains the byte sequence 13, 10 (CRLF), which is happening for this image.

I'm preparing a fix.

**Comment by pts** [comment]
Fixed in 5a75bbd043b62d151556d2b719e09f34cf1f1431.

**Comment by rbrito** [comment]
OK, thanks. I'm closing this bug, then.
