### ISSUE TITLE
/First and obj offsets 1 too high in generated /Type /ObjStdm

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#46]
I ran pdfsizeopt (commit 02450cf1773b0439bd604aa5adc87d04b4fdf2cf) on a PDF file created by pdfTeX and both atril (a poppler-based PDF viewer) and diffpdf (also poppler-based) refuse to open the resulting file.

I'm uploading both the file before and after processing with: `~/Downloads/pdfsizeopt/pdfsizeopt --use-pngout=no --use-multivalent=no E2000.pdf`

[E2000.pdf](https://github.com/pts/pdfsizeopt/files/1342708/E2000.pdf)
[E2000.pso.pdf](https://github.com/pts/pdfsizeopt/files/1342709/E2000.pso.pdf)

mupdf and gv (via ghostscript) *can* show the resulting file.

If there is anything else that I can provide, please let me know.

**Comment by pts** [comment]
Thank you for reporting this! Fixed in 3f511bf3ac0513c67da0f3d036003f5f24d6e22e.

The /Type /ObjStm object stream consists of numbers (obj num, obj offset) and then obj heads. Between the numbers and the obj heads whitespace may be necessary. The presence of this whitespace affects the /First value (should be the offset after the whitespace) and the obj offsets (emitted offset 0 should be after this whitespace). The bug was that pdfsizeopt generated incorrect, off-by-one /First value and obj offsets if the whitespace was present.
