### ISSUE TITLE
Lossy JPEG compression

### ISSUE THREAD

**Issue by pafnow** [pts/pdfsizeopt#67]
Hello,
Discovering this tool and seems quite promising!
However, I would like to process a better compression on my PDF file and would like to apply some change of JPEG quality and/or resolution.
Any idea if this is achievable with pdfsizeopt?

Thanks

**Comment by pts** [comment]
Thank you for asking about this feature! pdfsizeopt doesn't support any lossy conversions yet. Since pdfsizeopt is open source, it would be possible to implement this feature. The implementation would run e.g. `cjpeg -optimize -quality 50` on all image objects with `/Filter /DCTDecode`. Probably mozjpeg's cjpeg should be use instead of libjpeg's cjpeg, because the former creates smaller JPEGs. Some additional Python code has to be written to get the JPEG colorspace (RGB vs YCbCr) right.

This feature won't be implemented any time soon unless someone volunteers to do it.

As an additional optimization, pdfsizeopt could detect the maximum (centimeter) size of the each image in the PDF, and reduce the image dimensions (pixel width and height) if the size is small, i.e. pdfsizeopt could scale down all images to the user-specified DPI. This feature is even harder to implement, because for this the analysis of content streams and transformation matrices is needed, and this functionality is missing from pdfsizeopt, and it's a bit tricky to get it right.

**Comment by student-sx** [comment]
Do you have any recommendation for a pre- or post procession to reduce the files size even further using a lossy compression?
