### ISSUE TITLE
replace or augment pngout by zopflipng, optipng, advpng; improve Flate compression with Zopfli, ECT and advzip

### ISSUE THREAD

**Issue by DarkDimius** [pts/pdfsizeopt#7]
I did it locally for myself, by creating adding a `pngout` bash script to `$PATH` that invokes zopflipng.

**Comment by jordanius** [comment]
I did the exact same thing just a little over a week ago! Finally ended a very long search for a program that could apply Zopfli compression to zlib/deflate streams within a PDF file (which is what any PNG image becomes when embedded straight into a PDF losslessly). I was on the verge of jumping into learning all the details of PDF file structure so that I could just code my own solution when I finally realized that pdfsizeopt already has all the parts in place to parse the PDF and merge the recompressed sections back in while changing all the size references associated with the data stream (as compression tends to change the absolute size in bytes of most data it gets applied to). All the hard stuff was already done. I just needed to figure out how to make it send the zlib-compressed flate data out to a better program than PNGOUT, now that Zopfli compression has pretty much proved to be the superior option in every single use case.

However, I'd just like to share a really-well-hidden secret with anyone else who's looking into applying Zopfli compression - either to PNG files or to gzip/zlib/flate streams (in PDFs or elsewhere) - Google's Zopfli/ZopfliPNG package should no longer be your go-to Zopfli conversion program. Check out https://github.com/fhanau/Efficient-Compression-Tool - it's a little-known project that's had tons of development recently and consistently beats Google's original implementation both in filesize and in processing time. Oh, and it's also quite a bit easier to use (no messing around choosing filters and number of iterations - you just have a gzip-like 1-9 scale for performance vs time, and 9 times out of 10 the resulting filesize will be similar or even a few bytes smaller than a ZopfliPNG compression run with some crazy number of iterations - say, 500-1000. And it'll take 2% of the time to run that ZopfliPNG would have with those types of settings. Oh, and did I mention that it also happens to integrate MozJPEG into the same interface, so it's literally the best tool available for shrinking both PNGs and JPEGs, and that regardless of what crazy lengths you're willing to go to to shave off those last few bytes, this program is really all you need to get 100% of the way anyone's been able to go yet with these two file formats. A truly incredible little project that really deserves to get a lot more attention from people.

I'm attaching a simple 2-line bash script that, when saved to your $PATH under the name "pngout" does everything that you need it to do to redirect the flate streams pdfsizeopt exports for recompression to ECT instead of PNGOUT. Obviously, after the shebang, your first line will be a normal invoking of ECT with the options you want to use, feeding "$1" from the command line into ECT (which will store the filename of the file containing the input flate data). After that, you just need a simply copy command, "cp $1 $2", to make up for the fact that ECT is one of those compress-it-in-place-and-overwrite-the-original-file types of programs, whereas ZopfliPNG and PNGOUT both allow specifying an input and an output file location. That's all that's needed to rig this excellent little program to use the best deflate compressor available. If, for whatever reason, you're still using Google's ZopfliPNG instead of ECT, just use a single line like this in your bash file: "zopflipng -y -m --filters=p $1 $2" (and leave off the second line "cp" command - zopflipng doesn't need it since it lets you specify a separate output file instead of just automatically overwriting the input file like ECT - but really, check out ECT, it's only going to keep getting better the more people that discover it). Also, don't forget: if you already have the real PNGOUT program somewhere, rename it slightly just to avoid any issues.

Simply paste the following lines into Nano, save under the name "pngout", chmod 755 your new bash script, and move it onto your $PATH. That's all it takes to get pdfsizeopt to automatically start using ECT without even knowing it:


#!/bin/bash
ECT -3 -strip $1
cp $1 $2

**Comment by pts** [comment]
Thank you for writing the detailed and informational analysis.

If you want this to be included to pdfsizeopt, please send me a patch or a pull request.

**Comment by tetzank** [comment]
On a related note but not about recompressing PNG images: Here's a quick&dirty way how to use zopfli instead of zlib to compress (all?) the streams in the file. zopfli compresses a bit better.

https://github.com/tetzank/pdfsizeopt/commit/c69b7ee8a6599bd20a1af776f7c71bb09a303499

Sorry for the hack but i'm not really good in python. You probably have to integrate it and make it optional, maybe, in a better way.

**Comment by daviddoji** [comment]
are the indications provided by @jordanius already implemented in the code?

**Comment by pts** [comment]
@daviddoji: No, they aren't implemented. As soon as I have an update on alternative Flate and PNG compression integrated to pdfsizeopt, I'll update this issue.

Please note that I think none of zlib, Zopfli, advzip, ECT, PNGOUT, zopflipng, advpng is clearly superior, thus I won't be changing the default (zlib + PNGOUT) in pdfsizeopt. However, it may be useful to make these tools usable from pdfsizeopt with command-line flags, thus power users can choose for themselves. This is not high priority for me now, but I'll let you know here as soon as I make any progress.

**Comment by pts** [comment]
@DarkDimius, @jordanius, @tetzank: Thank you for your contributions! The insights and code provided make it much easier for me to decide and implement these features.

**Comment by rbrito** [comment]
Hi, @pts.

I have a (very dirty) patch that I use here with optipng (followed by advpng/advdef to get better results) and since I want to get better compression with tools only present in Debian, that's what I'm using personally.

It is only enabled when using a command-line switch, which means that the behavior of pdfsizeopt is not changed, unless the user wants it.

I can send this as a pull request if you want it as an interim solution to something better that is available on as many architectures as feasible (in the case of Debian).

**Comment by pts** [comment]
Command-lines for PNG recompression:

* `pngout -force %(sourcefnq)s %(targetfnq)s`
* `zopflipng -y -m --filters=p %(sourcefnq)s %(targetfnq)s`
* `optipng %(sourcefnq)s -o4 -fix -out %(targetfnq)s`
* `ECT -9 -strip $(targetfnq)s` (And copy source to target first.)
* `advpng -z3 %(targetfnq)s` (And copy source to target first.)
* `advpng -z4 %(targetfnq)s` (And copy source to target first.) This uses Zopfli.

**Comment by pts** [comment]
Feature added in 6c025f7959f0c4b84facc70e37b9d35acfb1ccf6. See the *Image optimizers* section in the README (https://github.com/pts/pdfsizeopt) for the command-line flag `
--use-image-optimizer=...` to enable these non-default image optimizers.
