### ISSUE TITLE
Does pdfsizeopt compress using something similiar to zipping files?

### ISSUE THREAD

**Issue by Keks-Dose** [pts/pdfsizeopt#74]
Very strange thing: all of a sudden Symantec Mail Security detects zip-files inside my PDFs. May it be the case that pdfsizeopt uses a compression algorithm which as well is being used to produce zip files? 

I'm writing LaTeX files, compile them, compress them with pdfsizeopt and mail them. On addressee (hey, an english word with three double letters!) uses Symantec Mail Security and this software complains:

> The message was marked for Deletion
>
>This was done due to the following Symantec Mail Security settings:
> Scan: Auto-Protect
> Rule: ZIP filter 
> Violating term(s): 
 >       *.ZIP (Matchlist name : Sample zip files)

**Comment by pts** [comment]
Thank you for reporting this!

pdfsizeopt doesn't add a virus or malware to its output PDF, its output is just as safe as the input.

This sounds like a false positive caused by a bug or misconfiguration in Symantec Mail Security, but I can confirm it only if I have the input and output PDF files. It's also useful to know whether Symatenc Mail Security triggers on the input PDF file (before processing by pdfsizeopt). Closing the bug until the PDF files get attached.

> pdfsizeopt uses a compression algorithm which as well is being used to produce zip files

This compression algorithm (used in ZIP, PNG, PDF, PostScript and in thousands of other places) is called deflate or flate, in PostScript and PDF files it's called `/FlateDecode` filter. pdfsizeopt, pdflatex and other PDF generators all use it.

Even if the input PDF of pdfsizeopt doesn't use `/FlateDecode`, the output PDF usually does, because one of the optimizations done by pdfsizeopt is recompressing all objects with flate, to save space. Please note that pdfsizeopt doesn't create ZIP files within its output PDF.
