### ISSUE TITLE
Releases numbering (SemVer ?) and new release for macOS

### ISSUE THREAD

**Issue by sbibauw** [pts/pdfsizeopt#81]
I was wondering if it would be possible to use some form of clear numbering for future releases (rather than using date): either actual semantic versioning or any variation of it (as long as 1.0 is higher than 0.9 ;-)). I saw that it was already the case for `sam2p`, but not for `pdfsizeopt` and `tif22pnm`.

The main reason for my request is that Homebrew relies on version numbering of the releases to determine whether there is an update. And currently, it wrongly interprets the date as the version number (https://github.com/pts/pdfsizeopt/releases/tag/2017-09-03d is understood as version `9.03`...).

Sidenote: the last release for macOS (2017-09-03d thus) is failing on the `deptest.pdf` (as I noticed by running `brew test-bot pts/utils/pdfsizeopt` which tries to process `deptest.pdf` as the main test for the software). Is it possible to release an updated one?

**Comment by pts** [comment]
Thank you for your work on adding pdfsizeopt to Homebrew!

Here is how pdfsizeopt packaging and releases work now for macOS:

* libexec.
  Contains precompiled executable binaries (e.g. *sam2p* and *pngout*) written in C and C++.
  Latest release for macOS as of now: https://github.com/pts/pdfsizeopt/releases/tag/2017-09-03d .
  New release once a year or even less often.
  To get the latest libexec, the user should consult https://github.com/pts/pdfsizeopt/blob/master/README.txt for the download link.
  I've recently added the download URL of the latest libexec to https://github.com/pts/pdfsizeopt/blob/master/latest_libexec.txt in a machine-readable format. I'll keep this file up to date.
  There is no useful version number. The release tag increases lexicographically.

* Python code in `pdfsizeopt.single`:
  A single executable file containing ZIP-ped Python code and a `#! /bin/sh` shebang prefix.
  Architecture-independent (works unmodified on Linux, macOS and Windows).
  The latest release is the file https://github.com/pts/pdfsizeopt/blob/master/pdfsizeopt.single .
  New release after each bugfix, can be as often as weekly.
  Doesn't have a version number.
  Identified by the Git commit ID (and to a lesser extent the file size).

I don't know enough about the specifics of Homebrew to give a good recommendation on how auto-updating should be implemented for pdfsizeopt in Homebrew. It looks like it won't be easy to make it work, because Homebrew seems to rely on increasing version numbers of a specific format, which pdfsizeopt doesn't have right now.

As the developer of pdfsizeopt, my preference is that Homebrew should autoupdate both the libexec and 
the Python code in `pdfsizeopt.single` shortly after a new version is pushed to GitHub. The corresponding URLs to watch for changes are:

* https://github.com/pts/pdfsizeopt/blob/master/latest_libexec.txt, the line starting with `macOS:`.
* https://github.com/pts/pdfsizeopt/blob/master/pdfsizeopt.single

If you have any specific recommendations to improve Homebrew integration, please let me know. You've already proposed version numbering, which I'm hereby rejecting, because it makes creating a release more complicated for me, i.e. adding manual steps to the release process. (I care more about releasing the Python code in `pdfsizeopt.single`, because that's happening more often.)

Please note that https://github.com/pts/pdfsizeopt/blob/master/README.txt already documents the official installation instructions for macOS. (This doesn't support autoupdate.) Homebrew is not one of the officially supported installation methods yet, thus improving Homebrew is best effort for me. I'm ready to help and make changes, but not in a way which makes my work harder in the future.

My recommendation for the users of pdfsizeopt is to use the binaries (e.g. *sam2p* and *pngout*) released in the libexec package of pdfsizeopt, rather then the binaries obtained from elsewhere (e.g. using Homebrew). This is because of compatibility reasons: new releases of the binaries may become incompatible with pdfsizeopt (this has happened multiple times already), and I don't have the free time to update pdfsizeopt each time a binary is changed in one of the dozens of operating system distributions beyond my control. Also I want to avoid frustration for the users when pdfsizeopt breaks for them: it's very frustrating for new users if pdfsizeopt is broken for days or weeks until I fix it, before the first time they are able to use it.

I wish I was able to give a larger time commitment on working with you to make autoupdates (with Homebrew and otherwise) easier for the users of pdfsizeopt.

**Comment by pts** [comment]
> the last release for macOS (2017-09-03d thus) is failing on the `deptest.pdf`.

Please file a separate bug for that, copy-pasting the full output of pdfsizeopt. Make sure you use the binaries in libexec for testing.

Please note that I don't have a computer running macOS, so it's expensive for me to do testing (I need to ask friends for favors).

**Comment by sbibauw** [comment]
Thank you very much for your extensive answer. I understand much better now the logic of the releases! There are various ways to manage this in Homebrew and beyond, but in any case, I really do not want to cause you any additional workload!

The first option is to put the `pdfsizeopt` brew formula as "HEAD-only", i.e. it ignores any "release" system and just takes the dev/bleeding edge version of the repository (currently, it downloads the whole git repo, runs `./mksingle.py` and uses the generated `pdfsizeopt.single` file as executable). It fits your recommended workflow. The only disadvantage would be that, as a bleeding edge/dev version, there is not much testing assuring that every version will work properly (and that Homebrew argues against HEAD only, for this unstability reason). But in any case, updating is extremely easy (it follows the git commits).

Regarding releases, I had not realized that it was mostly a release of the package of dependencies (I understand why it is thus only updated once a year, and why a semver numbering makes less sense). In the brew system, all dependencies are managed autonomously, so there is no need for a `libexec` package of binaries release. I understand your concern about new versions breaking compatibility for `pdfsizeopt`, but the risk is limited by the fact that `sam2p` and `tif22pnm` are taken from your personal repos, `pngout` has not moved an inch for 2 years, etc. But most of all, if a new version would break compatibility, it is relatively easy to specify an older version in the dependencies of the formula (e.g., `python@2` to have Python 2.7.14 if the default mac python would suddenly switch to python3). Well, all this to say that, anyway, the brew install method does not need a release of the deps binaries.

Now, I would still advocate a true release numbering system, but only for pdfsizeopt itself (do not bother updating more regularly the `libexec` package, and do not take it into account for numbering), even if it is just `1.#release`(bumping the last number as many times as necessary), to:

1. explicit the fact that there are no breaking changes (e.g. unless you pass to a different major version with `2.xxxx`)

2. release somewhat more tested/stable versions (if that is possible without additional workload)

This being said, I repeat: if you keep it this way, no problem, I'll just put the formula in head-only :-) 
And I can help you with testing on macOS if you need any help there.

**Comment by pts** [comment]
Thank you for the clarifications!

My recommendation: Make the formula HEAD-only, but don't run `./mksingle.py`. Use the `pdfsizeopt.single` file at HEAD. I consider it a stable release, and I regularly update it upon bugfixes. By using it gives you the benefit that Homebrew users will use the same code as regular users (who install pdfsizeopt by reading README.txt), and when they report bugs, it will be obvious for me which version they are running (pdfsizeopt prints the file size in the first log line).

Thank you for advocating for a release numbering system. Your suggestions make sense, but I'm not going to introduce it, because it would take free time away from me.

> making a little bit more explicit which version a new user not accustomed to git/vcs should download and use.

I don't understand which problem this would solve. The typical use case for a new user is: he types *pdfsizeopt* to Google, he gets https://github.com/pts/pdfsizeopt as the first result, he searches for *install* on that page, he finds and follows the installation instructions, and gets a working and stable version of pdfsizeopt running on his system in minutes. There is no confusion what to download, everything is explicity there in the installation instructions in *README.txt*, and it is formulated in a way non-developer, beginner users also understand, highlighting possible installation pitfalls. If you see a way to improve the installation instructions, please file a separate issue for that. Your feedback is very much appreciated.

> the risk is limited by the fact that sam2p and tif22pnm are taken from your personal repos

Indeed. FYI Some Linux distributions used to ship with a several-years-old sam2p. That's why a decided to distribute guaranteed-to-work binaries in libexec.

Also Ghostscript is changing quickly: some command-line flags are removed from newer versions, and some undocumented APIs pdfsizeopt uses are getting changed. I don't have the free time to adapt pdfsizeopt to each change in Ghostscript (they have a much larger full-time development team, I can't possibly keep up), and I don't want to have frustrated users, so I distribute a guaranteed-to-work Ghostscript binary in libexec.

**Comment by sbibauw** [comment]
OK, I understand your point about using `pdfsizeopt.single`.

What I meant about "making it a bit more explicit" (but you are right that instructions are clear, if read ;-)), was to actually use the "Release" functionality on Github to provide what users are expecting: the last +/- stable version of the program. Actually, this IS  exactly what you are doing with `pdfsizeopt.single`. 

Personally, what I would advocate is:
- a new release would only include `pdfsizeopt.single` (maybe rename it to `pdfsizeopt.sh` to make it clear that is it a shell script? just an idea as it is the first time I see a `.single` extension) (and the source code that Github automatically adds)
- create a separate repository for the dependencies package (e.g., `pdfsizeopt-deps` or `pdfsizeopt-libexec`) where you release only the `libexec` packages, at the same regularity as now

The install instructions would still be to:
- curl pdfsizeopt.single from this repo
- curl the libexec packages from the other repo
done :-)

Well, I just wanted to share my view. This being said, I'll stop wasting your time and adapt the `brew` install script to whatever workflow you prefer :-)

**Comment by pts** [comment]
Thank you for clarifying your suggestion! I understand it fully. I won't be changing my workflow yet though, because I can't see a benefit for the users or for my workflow.

The 2nd suggestion, i.e. moving the dependencies to a separate repository is easily doable, and it doesn't hurt my workflow. The reason why I'm not doing it is that I can't see a benefit for the users. Those who read the installation instructions would be unaffected. Those who don't will stillbe  confused about what to do with the download .zip and .tar.gz files containing the binaries (it's not obvious where to extract what), so it's a pain for them to make many guesses, and moving the downloads to a separate repository doesn't help that pain.

The 1st suggestion, i.e. uploading a copy of pdfsizeopt.single to each new release does hurt my workflow: it's extra manual steps (clicking): creating a new release, copying around the file, and uploading it, in addition to the existing steps (mksingle.py; git commit ...; git push). A compelling benefit for the users is needed to compensate for this, but I can't see that. Those who read the installation instructions would be unaffected. Those who don't will still be confused about what else to download and how to run pdfsizeopt.

FYI It's impossible to write a `curl -O https://github.com/pts/pdfsizeopt/releases/download/.../pdfsizeopt.single` command which points to the latest release (there is no way to formulate the `...`), so to keep the installation instructions simple, I'd have to continue keeping the latest copy of `pdfsizeopt.single` within the repo, because that has a stable URL (`https://raw.githubusercontent.com/pts/pdfsizeopt/master/pdfsizeopt.single` with the component `master` pointing to the latest version).

Maybe there is a benefit for the users which I've missed, and which would justify changing the workflow. If you see any, please let me know.

**Comment by sbibauw** [comment]
OK, I understand it :-) No problem
Thanks for the detailed explanations! :D 

(Note: for the `curl` targeting the last release, it is actually possible with a few pipes: https://stackoverflow.com/a/26738019 ;-) but you are right that it is actually easier with the single being in the repo.)
